version: '3.1'

services:
  postgres:
    container_name: mobicraft-postgres
    image: postgres:16.2
    networks:
      - mobicraft
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mobicraft
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    container_name: mobicraft_redis
    image: redis:latest
    networks:
      - mobicraft
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  minio:
    container_name: mobicraft_minio
    image: bitnami/minio:latest
    networks:
      - mobicraft
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio:/bitnami/minio/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 12345678
  typesense:
    container_name: mobicraft_typesense
    image: typesense/typesense:27.1
    networks:
      - mobicraft
    restart: always
    ports:
      - 8108:8108
    volumes:
      - typesense:/data
    environment:
      TYPESENSE_DATA_DIR: /data
      TYPESENSE_API_KEY: typesense
      TYPESENSE_LOG_LEVEL: debug
      TYPESENSE_ENABLE_CORS: "true"

volumes:
  postgres:
    name: mobicraft-postgres-db
  redis:
    name: mobicraft-redis
  minio:
    name: mobicraft-minio
  typesense:
    name: mobicraft-typesense

networks:
  mobicraft:
